### PR TITLE
fix(bridge): ignore uncaught exception

### LINKED ISSUE #63: fix(bridge): `Error: PollingBlockTracker - encountered an error while attempting to update latest block`
```
Error: PollingBlockTracker - encountered an error while attempting to update latest block:
undefined
    at PollingBlockTracker._performSync (/app/node_modules/eth-block-tracker/src/polling.js:51:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

### PR DESCRIPTION
**Pull request by moreal**
Maybe this resolves #63

### CODE REVIEW

File: bridge/src/index.ts [hunk 1]
```diff
@@ -24,6 +24,9 @@ import consoleStamp from 'console-stamp';
 import { AddressBanPolicy } from "./policies/address-ban";
 
 consoleStamp(console);
+
```
Comment (longfin) [inline bridge/src/index.ts:27]: How about adding a comment about #63 ?

**Review by longfin — APPROVED** [review]

File: bridge/src/index.ts (hunk 1 above)
Comment (moreal) [reply bridge/src/index.ts:27]: I added it in d9465a3
